name: Deploy to dev

on:
  release:
    types: [released]
  workflow_dispatch:
    inputs:
      tags:
        required: true
        description: 'Release Version'   

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: echo test